mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
# urlpatterns = [
#     # ex: /polls/
#     path('', views.index, name='index'),
#     # ex: /polls/5/
#     path('<int:question_id>/', views.detail, name='detail'),
#     # ex: /polls/5/results/
#     path('<int:question_id>/results/', views.results, name='results'),
#     # ex: /polls/5/vote/
#     path('<int:question_id>/vote/', views.vote, name='vote'),
# ]

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('signin/', views.signinview, name='signin'),
    path('signin/verify', views.signin, name='verify_user'),
    path('signup/', views.signup, name='signup'),
    path('signout/', views.signout, name='signout'),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    # def was_published_recently(self):
    #     return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
   
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
# from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.urls import reverse
from django.views import generic
from .models import Question, Choice
from django.utils import timezone
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


# def index(request):
#     return HttpResponse("Hello, world. You're at the polls index.")

# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     output = ', '.join([q.question_text for q in latest_question_list])
#     return HttpResponse(output)

# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     template = loader.get_template('polls/index.html')
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#     return HttpResponse(template.render(context, request))

# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'polls/index.html', context)

class IndexView(LoginRequiredMixin,generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'result'

    def get_queryset(self):
        q = Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
        context = {
            'latest_question_list' : q,
            'message' : 'success'

        }
        return context

# def detail(request, question_id):
#     return HttpResponse("You're looking at question %s." % question_id)

# def detail(request, question_id):
#     try:
#         question = Question.objects.get(pk=question_id)
#     except Question.DoesNotExist:
#         raise Http404("Question does not exist")
#     return render(request, 'polls/detail.html', {'question': question})

# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     context = {'question': question}
#     return render(request, 'polls/detail.html', context)

class DetailView(LoginRequiredMixin,generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    context_object_name = 'qquestion'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


# def results(request, question_id):
#     response = "You're looking at the results of question %s."
#     return HttpResponse(response % question_id)

# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     context =  {'question': question}
#     return render(request, 'polls/results.html', context)

class ResultsView(LoginRequiredMixin,generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

# def vote(request, question_id):
#     return HttpResponse("You're voting on question %s." % question_id)

	
def vote(request, question_id):
    if(request.user.is_authenticated):
        question = get_object_or_404(Question, pk=question_id)
        try:
            selected_choice = question.choice_set.get(pk=request.POST['choice'])
        except (KeyError, Choice.DoesNotExist):
            # Redisplay the question voting form.
            context = {
                'qquestion': question,
                'error_message': "You didn't select a choice.",
            }
            return render(request, 'polls/detail.html', context)
        else:
            selected_choice.votes += 1
            selected_choice.save()
            # Always return an HttpResponseRedirect after successfully dealing
            # with POST data. This prevents data from being posted twice if a
            # user hits the Back button.
            return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
    else:
        return HttpResponseRedirect(reverse('polls:signin'))

# User Authentication
def signinview(request):
	if(request.user.is_authenticated):
		return HttpResponseRedirect(reverse('polls:index'))
	else:
	    return render(request, 'polls/signin.html')

def signin(request):
    print('SIGNING IN')
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        # Redirect to a success page.
        return HttpResponseRedirect(reverse('polls:index'))
    else:
    	print('Details: ' + username + " " + password)
    	# Return an 'invalid login' error message
    	context = {'error_message': "Incorrect username or password."}
    	return render(request,'polls/signin.html',context)

def signout(request):
    logout(request)
    return HttpResponseRedirect(reverse('polls:signin'))

def signup(request):
    print('Signing up')
    if request.method == 'POST':
        f = UserCreationForm(request.POST)
        if f.is_valid():
            f.save()
            messages.success(request, 'Account created successfully')
            return redirect('polls:signin')

    else:
        f = UserCreationForm()
        return render(request,'polls/signin.html')

polls/templates/polls/base_site.html
{% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'polls/base.css' %}" />

<nav class="menu" tabindex="0">
	<div class="smartphone-menu-trigger"></div>
	<header class="avatar">
		{% load static %}
		<img src="{% static "polls/images/avatar.png" %}" alt="My image"/>
		{%if user.is_authenticated %}
			<h2> {{user.username }} </h2>
		{%endif%}
	</header>
	<ul>
		<li tabindex="0" class="icon-dashboard"><span>Dashboard</span></li>
		<li tabindex="0" class="icon-customers"><span>Customers</span></li>
		<li tabindex="0" class="icon-settings"><span>Settings</span></li>
		<a style="text-decoration:none; color: white" href="{% url 'polls:signout' %}"><li tabindex="0" class="icon-users"><span>Logout</span></li></a>
		
	</ul>
</nav>

<main>
	<div class="helper">
		{% block content %}{% endblock %}
	</div>
</main>

polls/templates/polls/detail.html
{% extends "polls/base_site.html" %}
<!-- <h1>
	{{ question.question_text }}
</h1>
<ul>
	{% for choice in question.choice_set.all %}
    	<li>
    		{{ choice.choice_text }}
    	</li>
	{% endfor %}
</ul> -->

{% block content %}
 <h1>{{ qquestion.question_text }}</h1>

{% if error_message %}<p> hello from the other side:<strong>{{error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' qquestion.id %}" method="post">
{% csrf_token %}
{% for choice in qquestion.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />

    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
    
{% endfor %}
<input type="submit" value="Vote" />
</form>
{% endblock %}

polls/templates/polls/index.html
{% extends "polls/base_site.html" %}

{% block content %}
	{{result.message}}
	{% if result.latest_question_list %}
	    <ul>
	    {% for question in result.latest_question_list %}
		<li>
			<a href="{% url 'polls:detail' question.id %}">
				{{ question.question_text }}
			</a>
		</li>
	    {% endfor %}
	    </ul>
	{% else %}
	    <p>No polls are available.</p>
	{% endif %}
{% endblock %}

polls/templates/polls/results.html
{% extends "polls/base_site.html" %}

{% block content %}
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}

polls/templates/polls/signin.html
{% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'polls/signin.css' %}" />

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<script type="text/javascript" src="{% static 'polls/signin.js' %}"></script>

{% if error_message %}
  <script type="text/javascript">console.log(error_message)</script>
  {{ error_message }}  
  {% endif %}
{% if messages %}
    <ul>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
<!-- Form-->
<div class="form">
  <div class="form-toggle"></div>
  <div class="form-panel one">
    <div class="form-header">
      <h1>Account Login</h1>
    </div>
    <div class="form-content">
      <form action="{% url 'polls:verify_user'%}" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="username">Username</label>
          <input type="text" id="username" name="username" required="required"/>
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          <input type="password" id="password" name="password" required="required"/>
        </div>
        <div class="form-group">
          <label class="form-remember">
            <input type="checkbox"/>Remember Me
          </label><a class="form-recovery" href="#">Forgot Password?</a>
        </div>
        <div class="form-group">
          <button type="submit">Log In</button>
        </div>
      </form>
    </div>
  </div>
  <div class="form-panel one">
    <div class="form-header">
      <h1>Register Account</h1>
    </div>
    <div class="form-content">
      <form action="{% url 'polls:signup'%}" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="username">Username</label>
          <input type="text" id="username" name="username" required="required"/>
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          <input type="password" id="password" name="password" required="required"/>
        </div>
        <div class="form-group">
          <label for="cpassword">Confirm Password</label>
          <input type="password" id="cpassword" name="cpassword" required="required"/>
        </div>
        <div class="form-group">
          <label for="email">Email Address</label>
          <input type="email" id="email" name="email" required="required"/>
        </div>
        <div class="form-group">
          <button type="submit">Register</button>
        </div>
      </form>
    </div>
  </div>
</div>